services:
  postgres:
    image: postgres:16-alpine
    container_name: vet-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend:/docker-entrypoint-initdb.d

  redis:
    image: redis:alpine
    container_name: vet-redis
    ports:
      - "${REDIS_PORT}:6379"

  api:
    build: ./api
    container_name: vet-api
    environment:
      # Construimos la URL dinámicamente usando las variables del .env
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379
      PORT: 3000
    ports:
      - "${API_PORT_EXTERNAL}:3000"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    container_name: vet-frontend
    environment:
      # URL de la API para que el Front sepa a dónde apuntar
      NEXT_PUBLIC_API_URL: http://localhost:${API_PORT_EXTERNAL}
    ports:
      - "${FRONT_PORT_EXTERNAL}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  pgdata: